//////////////////////////////////////////////////////////////////////////////////////////
//											//
//	Creado por:									//
//	Gustavo Andrés Uribe Gomez							//
//	Luis Miguel Collazos V.								//
//	Cesar G. Chaves A.								//
//	Flavio Andres Martinez Erazo							//
//	Andrés Felipe Escallón Portilla							//
//	Jose Wilmer Castillo Obando							//
//	Fabian Leonidas Mosquera Palta							//
//	Jorege David Moncayo Bravo							//
//											//
//--------------------------------------------------------------------------------------//
//											//
//	archivos.h:									//
//	Cabecera que contiene las funciones propias para el manejo de archivos.		//
//											//
//////////////////////////////////////////////////////////////////////////////////////////

#ifndef CABECERA_ARCHIVOS
#define CABECERA_ARCHIVOS

#include <fstream.h>

int buscar(char*,char*);

#endif

